name: customer_360
version: 1.0.0
config-version: 2
profile: customer_360
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  customer_360:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    mart:
      +materialized: table
    features:
      +materialized: incremental
    metrics:
      +materialized: table