-- ============================================================
-- 01_roles_and_warehouses.sql
-- Run as: SYSADMIN
-- ============================================================

USE ROLE SYSADMIN;

-- Databases and schemas
CREATE DATABASE IF NOT EXISTS CUSTOMER_PLATFORM;

CREATE SCHEMA IF NOT EXISTS CUSTOMER_PLATFORM.RAW;
CREATE SCHEMA IF NOT EXISTS CUSTOMER_PLATFORM.STAGE;
CREATE SCHEMA IF NOT EXISTS CUSTOMER_PLATFORM.CORE;
CREATE SCHEMA IF NOT EXISTS CUSTOMER_PLATFORM.MART;
CREATE SCHEMA IF NOT EXISTS CUSTOMER_PLATFORM.FEATURES;
CREATE SCHEMA IF NOT EXISTS CUSTOMER_PLATFORM.ML;
CREATE SCHEMA IF NOT EXISTS CUSTOMER_PLATFORM.MONITORING;

-- Warehouses
CREATE WAREHOUSE IF NOT EXISTS WH_INGEST
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_DBT_TRANSFORM
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_ML
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS WH_ADHOC
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 30
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Roles
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS INGEST_ROLE;
CREATE ROLE IF NOT EXISTS TRANSFORMER_ROLE;
CREATE ROLE IF NOT EXISTS ML_ROLE;
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS MONITOR_ROLE;

GRANT ROLE INGEST_ROLE      TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER_ROLE TO ROLE SYSADMIN;
GRANT ROLE ML_ROLE          TO ROLE SYSADMIN;
GRANT ROLE ANALYST_ROLE     TO ROLE SYSADMIN;
GRANT ROLE MONITOR_ROLE     TO ROLE SYSADMIN;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE WH_INGEST        TO ROLE INGEST_ROLE;
GRANT USAGE ON WAREHOUSE WH_DBT_TRANSFORM TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON WAREHOUSE WH_ML            TO ROLE ML_ROLE;
GRANT USAGE ON WAREHOUSE WH_ADHOC         TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE WH_ADHOC         TO ROLE MONITOR_ROLE;

-- Database grants
GRANT USAGE ON DATABASE CUSTOMER_PLATFORM TO ROLE INGEST_ROLE;
GRANT USAGE ON DATABASE CUSTOMER_PLATFORM TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON DATABASE CUSTOMER_PLATFORM TO ROLE ML_ROLE;
GRANT USAGE ON DATABASE CUSTOMER_PLATFORM TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE CUSTOMER_PLATFORM TO ROLE MONITOR_ROLE;

-- Schema grants — INGEST_ROLE
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.RAW TO ROLE INGEST_ROLE;
GRANT CREATE TABLE ON SCHEMA CUSTOMER_PLATFORM.RAW TO ROLE INGEST_ROLE;
GRANT CREATE STAGE ON SCHEMA CUSTOMER_PLATFORM.RAW TO ROLE INGEST_ROLE;
GRANT CREATE PIPE  ON SCHEMA CUSTOMER_PLATFORM.RAW TO ROLE INGEST_ROLE;

-- Schema grants — TRANSFORMER_ROLE
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.RAW        TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.STAGE      TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.CORE       TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.MART       TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.FEATURES   TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.ML         TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.MONITORING TO ROLE TRANSFORMER_ROLE;

GRANT CREATE TABLE ON SCHEMA CUSTOMER_PLATFORM.STAGE      TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TABLE ON SCHEMA CUSTOMER_PLATFORM.CORE       TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TABLE ON SCHEMA CUSTOMER_PLATFORM.MART       TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TABLE ON SCHEMA CUSTOMER_PLATFORM.FEATURES   TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TABLE ON SCHEMA CUSTOMER_PLATFORM.ML         TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TABLE ON SCHEMA CUSTOMER_PLATFORM.MONITORING TO ROLE TRANSFORMER_ROLE;
GRANT CREATE VIEW  ON SCHEMA CUSTOMER_PLATFORM.STAGE      TO ROLE TRANSFORMER_ROLE;
GRANT CREATE VIEW  ON SCHEMA CUSTOMER_PLATFORM.MART       TO ROLE TRANSFORMER_ROLE;

-- Schema grants — ML_ROLE
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.FEATURES TO ROLE ML_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.ML       TO ROLE ML_ROLE;
GRANT CREATE TABLE ON SCHEMA CUSTOMER_PLATFORM.ML TO ROLE ML_ROLE;

-- Schema grants — ANALYST_ROLE
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.MART     TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.FEATURES TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA CUSTOMER_PLATFORM.ML       TO ROLE ANALYST_ROLE;

-- Future grants
GRANT FUTURE SELECT ON TABLES IN SCHEMA CUSTOMER_PLATFORM.RAW      TO ROLE TRANSFORMER_ROLE;
GRANT FUTURE SELECT ON TABLES IN SCHEMA CUSTOMER_PLATFORM.STAGE    TO ROLE TRANSFORMER_ROLE;
GRANT FUTURE SELECT ON TABLES IN SCHEMA CUSTOMER_PLATFORM.MART     TO ROLE TRANSFORMER_ROLE;
GRANT FUTURE SELECT ON TABLES IN SCHEMA CUSTOMER_PLATFORM.FEATURES TO ROLE TRANSFORMER_ROLE;
GRANT FUTURE SELECT ON TABLES IN SCHEMA CUSTOMER_PLATFORM.ML       TO ROLE TRANSFORMER_ROLE;
GRANT FUTURE SELECT ON TABLES IN SCHEMA CUSTOMER_PLATFORM.FEATURES TO ROLE ML_ROLE;
GRANT FUTURE SELECT ON TABLES IN SCHEMA CUSTOMER_PLATFORM.MART     TO ROLE ANALYST_ROLE;
GRANT FUTURE SELECT ON TABLES IN SCHEMA CUSTOMER_PLATFORM.FEATURES TO ROLE ANALYST_ROLE;
GRANT FUTURE SELECT ON TABLES IN SCHEMA CUSTOMER_PLATFORM.ML       TO ROLE ANALYST_ROLE;