-- ============================================================
-- 04_raw_tables.sql
-- Run as: SYSADMIN
-- ============================================================

USE ROLE SYSADMIN;
USE DATABASE CUSTOMER_PLATFORM;
USE SCHEMA RAW;
USE WAREHOUSE WH_INGEST;

CREATE TABLE IF NOT EXISTS RAW.CUSTOMERS (
    CUSTOMER_ID         VARCHAR(50),
    FIRST_NAME          VARCHAR(100),
    LAST_NAME           VARCHAR(100),
    EMAIL               VARCHAR(255),
    PHONE               VARCHAR(30),
    DATE_OF_BIRTH       DATE,
    GENDER              VARCHAR(20),
    SIGNUP_DATE         DATE,
    ACQUISITION_CHANNEL VARCHAR(50),
    REGION              VARCHAR(50),
    CITY                VARCHAR(100),
    STATE               VARCHAR(50),
    POSTAL_CODE         VARCHAR(20),
    COUNTRY             VARCHAR(50),
    LOYALTY_TIER        VARCHAR(30),
    IS_ACTIVE           BOOLEAN,
    _SOURCE_FILE        VARCHAR(500),
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.ORDERS (
    ORDER_ID                 VARCHAR(50),
    CUSTOMER_ID              VARCHAR(50),
    ORDER_DATE               TIMESTAMP_NTZ,
    ORDER_STATUS             VARCHAR(30),
    TOTAL_AMOUNT             NUMBER(12,2),
    DISCOUNT_AMOUNT          NUMBER(12,2),
    TAX_AMOUNT               NUMBER(12,2),
    SHIPPING_AMOUNT          NUMBER(12,2),
    PAYMENT_METHOD           VARCHAR(30),
    CHANNEL                  VARCHAR(30),
    PROMO_CODE               VARCHAR(50),
    SHIPPING_ADDRESS_CITY    VARCHAR(100),
    SHIPPING_ADDRESS_STATE   VARCHAR(50),
    SHIPPING_ADDRESS_COUNTRY VARCHAR(50),
    _SOURCE_FILE             VARCHAR(500),
    _LOADED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.ORDER_ITEMS (
    ORDER_ITEM_ID   VARCHAR(50),
    ORDER_ID        VARCHAR(50),
    PRODUCT_ID      VARCHAR(50),
    QUANTITY        NUMBER(6,0),
    UNIT_PRICE      NUMBER(10,2),
    DISCOUNT_AMOUNT NUMBER(10,2),
    LINE_TOTAL      NUMBER(12,2),
    CATEGORY        VARCHAR(100),
    _SOURCE_FILE    VARCHAR(500),
    _LOADED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.TRANSACTIONS (
    TRANSACTION_ID    VARCHAR(50),
    ORDER_ID          VARCHAR(50),
    CUSTOMER_ID       VARCHAR(50),
    TRANSACTION_DATE  TIMESTAMP_NTZ,
    AMOUNT            NUMBER(12,2),
    CURRENCY          VARCHAR(10),
    PAYMENT_METHOD    VARCHAR(30),
    CARD_BIN          VARCHAR(10),
    PAYMENT_STATUS    VARCHAR(30),
    FAILURE_REASON    VARCHAR(100),
    DEVICE_ID         VARCHAR(100),
    DEVICE_TYPE       VARCHAR(30),
    IP_ADDRESS        VARCHAR(50),
    GEO_COUNTRY       VARCHAR(50),
    GEO_CITY          VARCHAR(100),
    MERCHANT_CATEGORY VARCHAR(50),
    IS_INTERNATIONAL  BOOLEAN,
    _SOURCE_FILE      VARCHAR(500),
    _LOADED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.CLICKSTREAM (
    EVENT_ID           VARCHAR(100),
    SESSION_ID         VARCHAR(100),
    CUSTOMER_ID        VARCHAR(50),
    ANONYMOUS_ID       VARCHAR(100),
    EVENT_TIMESTAMP    TIMESTAMP_NTZ,
    EVENT_TYPE         VARCHAR(50),
    PAGE_URL           VARCHAR(1000),
    PRODUCT_ID         VARCHAR(50),
    CATEGORY           VARCHAR(100),
    SEARCH_TERM        VARCHAR(500),
    DEVICE_TYPE        VARCHAR(30),
    CHANNEL            VARCHAR(30),
    REFERRER           VARCHAR(500),
    DWELL_TIME_SECONDS NUMBER(8,0),
    _SOURCE_FILE       VARCHAR(500),
    _LOADED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.CAMPAIGNS (
    CAMPAIGN_RESPONSE_ID VARCHAR(100),
    CUSTOMER_ID          VARCHAR(50),
    CAMPAIGN_ID          VARCHAR(50),
    CAMPAIGN_NAME        VARCHAR(200),
    CAMPAIGN_TYPE        VARCHAR(50),
    SENT_AT              TIMESTAMP_NTZ,
    OPENED_AT            TIMESTAMP_NTZ,
    CLICKED_AT           TIMESTAMP_NTZ,
    CONVERTED_AT         TIMESTAMP_NTZ,
    UNSUBSCRIBED_AT      TIMESTAMP_NTZ,
    CONVERSION_AMOUNT    NUMBER(12,2),
    _SOURCE_FILE         VARCHAR(500),
    _LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW.PRODUCTS (
    PRODUCT_ID   VARCHAR(50),
    PRODUCT_NAME VARCHAR(500),
    CATEGORY     VARCHAR(100),
    SUBCATEGORY  VARCHAR(100),
    BRAND        VARCHAR(100),
    BASE_PRICE   NUMBER(10,2),
    COST_PRICE   NUMBER(10,2),
    PRICE_BAND   VARCHAR(20),
    IS_ACTIVE    BOOLEAN,
    CREATED_AT   TIMESTAMP_NTZ,
    _SOURCE_FILE VARCHAR(500),
    _LOADED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS MONITORING.PIPELINE_AUDIT (
    AUDIT_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
    PIPELINE_NAME    VARCHAR(200),
    LAYER            VARCHAR(50),
    STEP             VARCHAR(200),
    STATUS           VARCHAR(30),
    ROWS_LOADED      NUMBER,
    ROWS_FAILED      NUMBER,
    STARTED_AT       TIMESTAMP_NTZ,
    COMPLETED_AT     TIMESTAMP_NTZ,
    DURATION_SECONDS NUMBER,
    ERROR_MESSAGE    VARCHAR(2000),
    CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);